import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[shell]
program = "tmux"
args = ["new", "-A", "-D", "-s", "vanzuh"]

[font]
normal = { family = "JetBrainsMonoNL NF", style = "Regular"}

[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[cursor]
vi_mode_style = { shape = "Beam", blinking ="On"  }
style = { shape = "Beam", blinking ="On"  }
