import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

[shell]
program = "tmux"
args = ["new", "-A", "-D", "-s", "vanzuh"]

[font]
normal = { family = "JetBrainsMonoNL NF", style = "Regular"}

[window]
padding = { x = 10, y = 10 }
opacity = 0.8

[cursor]
vi_mode_style = { shape = "Beam", blinking ="On"  }
style = { shape = "Beam", blinking ="On"  }

# [colors]
# indexed_colors = [{ index = 16, color = '0xF5D0D0' }, { index = 17, color = '0x141719' }]
#
# [colors.primary]
# background = '0x0A0D0F'
# foreground = '0xFFF2FF'
#
# [colors.cursor]
# text = '0x0A0D0F'
# cursor = '0xFFF2FF'
#
# [colors.normal]
# black = '0x191C1E'
# red = '0xFFB2AD'
# green = '0xB4F8C8'
# yellow = '0xFFFFC1'
# blue = '0xBFFBF9'
# magenta = '0xFFBDCB'
# cyan = '0x7ed1f6'
# white = '0xFFFCFF'
#
# [colors.bright]
# black = '0x232628'
# red = '0xffbcb7'
# green = '0xbeffd2'
# yellow = '0xffffcb'
# blue = '0xc9ffff'
# magenta = '0xffc7d5'
# cyan = '0x92e5ff'
# white = '0xffffff'
